email:
  subject: "Your One-Time Code"
  body: |
    Hello,

    Your one-time code is: {{ code }}

    Please use this code to complete your verification process. This code is valid for 10 minutes.

    If you did not request this code, please ignore this email.

    Thank you,
    The Team
  sender: "no-reply@example.com"
  recipient: "{{ user_email }}"