name: Detect Changes and Trigger Python Script

on:
  push:
    paths:
      - iterable_asset_definitions/**

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run change detector script
        run: |
          git diff --name-status HEAD^ HEAD > changes.txt
          python main.py changes.txt
